name: Build and Test

# Run workflow whenever code is pushed or a pull request is opened
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # The environment GitHub will use (Linux machine)

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (for your project)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project using Maven or Gradle
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run tests
      - name: Run Tests
        run: mvn test
